DROP TABLE IF EXISTS Cat;
DROP TABLE IF EXISTS Dog;

CREATE TABLE Cat (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT,
    age INTEGER NOT NULL,
    favorite_food TEXT,
    speak_counter INTEGER NOT NULL
);

CREATE TABLE Dog (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT,
    age INTEGER NOT NULL,
    favorite_food TEXT,
    speak_counter INTEGER NOT NULL
);

